export const ERROR_CODE = {
  validationFailed: 'VALIDATION_FAILED',
  invalidRequest: 'INVALID_REQUEST',
  resourceNotFound: 'RESOURCE_NOT_FOUND',
  conflict: 'CONFLICT',
  internalServerError: 'INTERNAL_SERVER_ERROR',
  authInvalidCredentials: 'AUTH_INVALID_CREDENTIALS',
  authTokenMissing: 'AUTH_TOKEN_MISSING',
  authTokenInvalid: 'AUTH_TOKEN_INVALID',
  authTokenExpired: 'AUTH_TOKEN_EXPIRED',
  authRefreshTokenInvalid: 'AUTH_REFRESH_TOKEN_INVALID',
  authForbidden: 'AUTH_FORBIDDEN',
  preferenceKeywordDuplicated: 'PREFERENCE_KEYWORD_DUPLICATED',
  preferenceKeywordNotFound: 'PREFERENCE_KEYWORD_NOT_FOUND',
  preferenceRepositoryDuplicated: 'PREFERENCE_REPOSITORY_DUPLICATED',
  preferenceRepositoryNotFound: 'PREFERENCE_REPOSITORY_NOT_FOUND',
  preferenceRepositoryFormatInvalid: 'PREFERENCE_REPOSITORY_FORMAT_INVALID',
  briefingNotFound: 'BRIEFING_NOT_FOUND',
  briefingAlreadyInProgress: 'BRIEFING_ALREADY_IN_PROGRESS',
  briefingCreateFailed: 'BRIEFING_CREATE_FAILED',
  briefingPartialCreated: 'BRIEFING_PARTIAL_CREATED',
  briefingSummaryFailed: 'BRIEFING_SUMMARY_FAILED',
  savedArticleDuplicated: 'SAVED_ARTICLE_DUPLICATED',
  savedArticleNotFound: 'SAVED_ARTICLE_NOT_FOUND',
  externalGithubFailed: 'EXTERNAL_GITHUB_FAILED',
  externalHackerNewsFailed: 'EXTERNAL_HACKER_NEWS_FAILED',
  externalDevtoFailed: 'EXTERNAL_DEVTO_FAILED',
  externalRateLimited: 'EXTERNAL_RATE_LIMITED',
  externalTimeout: 'EXTERNAL_TIMEOUT',
  aiSummaryFailed: 'AI_SUMMARY_FAILED',
  aiRateLimited: 'AI_RATE_LIMITED',
  aiTimeout: 'AI_TIMEOUT',
  streamTokenInvalid: 'STREAM_TOKEN_INVALID',
  streamTokenExpired: 'STREAM_TOKEN_EXPIRED',
  streamNotFound: 'STREAM_NOT_FOUND',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]

export const SAFE_ERROR_MESSAGE: Record<ErrorCode, string> = {
  [ERROR_CODE.validationFailed]: '입력값을 다시 확인해 주세요.',
  [ERROR_CODE.invalidRequest]: '요청 형식이 올바르지 않습니다.',
  [ERROR_CODE.resourceNotFound]: '요청한 항목을 찾을 수 없습니다.',
  [ERROR_CODE.conflict]: '이미 처리된 요청이거나 중복된 항목입니다.',
  [ERROR_CODE.internalServerError]: '잠시 후 다시 시도해 주세요.',
  [ERROR_CODE.authInvalidCredentials]: '이메일 또는 비밀번호를 확인해 주세요.',
  [ERROR_CODE.authTokenMissing]: '로그인이 필요합니다.',
  [ERROR_CODE.authTokenInvalid]: '로그인이 필요합니다.',
  [ERROR_CODE.authTokenExpired]: '로그인이 만료되었습니다.',
  [ERROR_CODE.authRefreshTokenInvalid]: '다시 로그인해 주세요.',
  [ERROR_CODE.authForbidden]: '접근 권한이 없습니다.',
  [ERROR_CODE.preferenceKeywordDuplicated]: '이미 등록한 키워드입니다.',
  [ERROR_CODE.preferenceKeywordNotFound]: '키워드를 찾을 수 없습니다.',
  [ERROR_CODE.preferenceRepositoryDuplicated]: '이미 등록한 저장소입니다.',
  [ERROR_CODE.preferenceRepositoryNotFound]: '저장소를 찾을 수 없습니다.',
  [ERROR_CODE.preferenceRepositoryFormatInvalid]:
    '저장소는 owner/repo 형식으로 입력해 주세요.',
  [ERROR_CODE.briefingNotFound]: '브리핑을 찾을 수 없습니다.',
  [ERROR_CODE.briefingAlreadyInProgress]:
    '이미 생성 중인 브리핑이 있습니다.',
  [ERROR_CODE.briefingCreateFailed]: '브리핑 생성을 시작하지 못했습니다.',
  [ERROR_CODE.briefingPartialCreated]:
    '일부 출처를 제외하고 브리핑이 생성되었습니다.',
  [ERROR_CODE.briefingSummaryFailed]: 'AI 요약 생성에 실패했습니다.',
  [ERROR_CODE.savedArticleDuplicated]: '이미 저장한 글입니다.',
  [ERROR_CODE.savedArticleNotFound]: '저장한 글을 찾을 수 없습니다.',
  [ERROR_CODE.externalGithubFailed]: 'GitHub 수집에 실패했습니다.',
  [ERROR_CODE.externalHackerNewsFailed]: 'Hacker News 수집에 실패했습니다.',
  [ERROR_CODE.externalDevtoFailed]: 'DEV.to 수집에 실패했습니다.',
  [ERROR_CODE.externalRateLimited]: '외부 서비스 요청 한도를 초과했습니다.',
  [ERROR_CODE.externalTimeout]: '외부 서비스 응답이 지연되고 있습니다.',
  [ERROR_CODE.aiSummaryFailed]: 'AI 요약 생성에 실패했습니다.',
  [ERROR_CODE.aiRateLimited]: 'AI 요청 한도를 초과했습니다.',
  [ERROR_CODE.aiTimeout]: 'AI 응답이 지연되고 있습니다.',
  [ERROR_CODE.streamTokenInvalid]: '브리핑 진행 연결 권한이 없습니다.',
  [ERROR_CODE.streamTokenExpired]: '브리핑 진행 연결 시간이 만료되었습니다.',
  [ERROR_CODE.streamNotFound]: '브리핑 진행 상태를 찾을 수 없습니다.',
}
